#! /bin/sh

MCGCRAFTPATH=~/MCG_CRAFT

python3 "$MCGCRAFTPATH/mcgcraft.py" --whitelist "['0.0.0.0/0','::/0']" --name "Demo Server" --public True --mobspawning False --host play.mcgcraft.de --worldtype "BeispielWelt_Biome" "$@"
exit "$?"
