# A texturepack file contains all information that is game specific and important to the client

{
"TEXTURE_SIDE_LENGTH" : 16,
   #["Name",               transparenz,  icon, [( oben), (unten), ( vorne), ( hinten), ( links), ( rechts)]],
"TEXTURE_INFO" : [
    ["GRASS",                    False,     2, [( 0, 2), ( 0, 0), ( 0, 1)]],
    ["SAND",                     False,     0, [( 1, 0)]],
    ["BRICK",                    False,     0, [( 3, 0)]],
    ["STONE",                    False,     0, [( 2, 0)]],
    ["DIRT",                     False,     0, [( 0, 0)]],
    ["STEIN",                    False,     0, [( 5, 0)]],
    ["HOLZ",                     False,     0, [( 4, 0), ( 4, 0), ( 4, 1)]],
    ["LAUB",                     False,     0, [(14, 0)]],
    ["GREEN" ,                   False,     0, [( 0, 2)]],
    ["HOLZBRETTER" ,             False,     0, [( 7, 0)]],
    #bis hier INVENTAR 1
    ["BRUCHSTEIN" ,              False,     0, [(10, 0)]],
    ["SCHNEEERDE" ,              False,     0, [( 8, 2), ( 0, 0), ( 8, 1)]],
    ["SCHNEE" ,                  False,     0, [(15, 0)]],
    ["WOLLE" ,                   False,     0, [( 8, 2)]],
    ["STEINZIEGEL" ,             False,     0, [(12, 0)]],
    ["SCHILDBLOCK" ,             False,     0, [(13, 0)]],

    #bis hier INVENTAR 2
    ["GELB" ,                    False,     0, [( 0,11)]],
    ["HELLGRUN" ,                False,     0, [( 1,11)]],
    ["GRUN" ,                    False,     0, [( 2,11)]],
    ["TURKIES" ,                 False,     0, [( 3,11)]],
    ["SCHWARZ" ,                 False,     0, [( 0,12)]],
    ["LILA" ,                    False,     0, [( 7,11)]],
    ["ORANGE" ,                  False,     0, [( 5,12)]],
    ["HELLBLAU" ,                False,     0, [(11,12)]],
    ["ROT" ,                     False,     0, [(11,11)]],
    ["HELLROT" ,                 False,     0, [(12,11)]],
    ["ROSA" ,                    False,     0, [(13,11)]],
    ["HELLGRAU",                 False,     0, [(12,12)]],
    ["DUNKELGRUN" ,              False,     0, [( 4,11)]],
    ["GRAU" ,                    False,     0, [( 8,11)]],
    ["DUNKELGRAU" ,              False,     0, [( 6,11)]],
    ["HELLORANGE" ,              False,     0, [( 6,12)]],
    ["BRAUN" ,                   False,     0, [( 3,12)]],
    ["WEISS" ,                   False,     0, [(13,12)]],
    #bis hier INVENTAR FARBEN

    ["DIAMANT" ,                 False,     0, [( 6, 2)]],
    ["REDSTONE" ,                False,     0, [( 7, 2)]],
    ["GOLD" ,                    False,     0, [( 5, 2)]],
    ["GOLDERZ" ,                 False,     0, [( 3, 2)]],
    ["IRON" ,                    False,     0, [( 6, 1), ( 6, 1), (11, 0)]],
    ["SMARAGTBLOCK" ,            False,     0, [( 1, 1)]],
    ["SMARAGTERZ" ,              False,     0, [( 2, 2)]],
    ["DIAMANTERZ" ,              False,     0, [( 2, 1)]],
    ["EISENERZ" ,                False,     0, [( 7, 1)]],
    ["KOHLEERZ" ,                False,     0, [( 1, 2)]],
    ["Quarzsaule",               False,     0, [( 9, 2)]],
    #Erze
    ["GESICHT" ,                 False,     2, [( 1,15), (1 ,15), ( 1,14), ( 3,14), ( 0,14), ( 2,14)]],
    ["CREEPER" ,                 False,     0, [( 3,13), (3 ,13), ( 2,13)]],
    ["Zombie" ,                  False,     0, [( 1,15), (1 ,15), ( 0,13)]],
    ["Skelett",                  False,     0, [(15, 0), (15, 0), ( 0,15)]],
    ["Schaf",                    False,     0, [(13,12), (13,12), (13,12), (13,12), (13,12), ( 4,13)]],
    # Gesichter
    ["Schafbeine",               False,     0, [(13,12), ( 0,12), ( 5,13)]],
    # Beine
    ["Commandblock",             False,     0, [(10, 1)]],
    ["Fruhlingsgrass",           False,     2, [( 7, 3), ( 0, 0), ( 0, 1)]],
    ["Fruhlingslaub",            False,     0, [(11, 1)]],
    ["GLAS",                     False,     0, [( 9, 0)]],
    ["TNT",                      False,     2, [(14, 1), (14, 1), (15, 1)]],
    ["Netherstone",              False,     0, [( 7, 4)]],
    ["Lapiserz",                 False,     0, [( 7, 3)]],
    ["Bucherregal",              False,     2, [( 7, 0), ( 7, 0), (15, 2)]],
    ["Obsidian" ,                False,     0, [( 9, 4)]],
    ["Prismarin",                False,     0, [(14, 7)]],
    ["Myzeln",                   False,     2, [( 9, 5), ( 0, 0), ( 8, 5)]],
    ["Rissige_Steinziegel",      False,     0, [(11, 6)]],    
    ["Steinziegel",              False,     0, [(11, 8)]],
    ["Gemeisselter_Steinziegel", False,     0, [(11, 7)]],
    ["CHEST",                    False,     2, [(15, 9), (14, 9), (14,10), (15,10), (15,10), (15,10)]],
    ["missing_texture",          False,     0, [(15,15)]],
    ["HERZ",                     True ,     1, [(14,15), (12, 6), (14,15)]], 
    ["DOORTOP",                  False,     0, [(12, 6)]],
    ["DOORSTEP",                 False,     0, [(0 , 4)]],
    ["DOORBOTTOM",               False,     0, [(0 , 4)]],
    ],

"ENTITY_MODELS": {
    "PLAYER":{
        "head":[((0,-0.6,0),(0,0.6,0),(1,1,1),"GESICHT")],
        "body":[((0,-1,0),(0,0,0),(0.8,1,0.4),"<<random>>")],
        "legl":[],
        "legr":[],
        },
    "SCHAF":{
        "head":[((0,0,0),(0,0.8,-0.75),(0.7,0.7,0.6),"Schaf")],
        "body":[((0,0,0),(0,0,0),(1.1,1.1,1.7),"WEISS"),
                ((0,0,0),(0,0.1,0.9),(0.3,0.4,0.2),"WEISS")],
        "legl":[((0.35,-0.3,0.55),(0,-0.5,0),(0.35,1,0.35),"Schafbeine"),
                ((0.35,-0.3,-0.55),(0,-0.5,0),(0.35,1,0.35),"Schafbeine")],
        "legr":[((-0.35,-0.3,-0.55),(0,-0.5,0),(0.35,1,0.35),"Schafbeine"),
                ((-0.35,-0.3,0.55),(0,-0.5,0),(0.35,1,0.35),"Schafbeine")],
        }

    },

}
